from src.fetcher import fetch_trending
from src.analyzer import analyze_project
from src.notifier import send_report


def _esc(text):
    return (text or "").replace("|", "\\|").replace("\n", " ")


def build_report(repos):
    lines = [
        "# Weekly Open Source Trending Report",
        "",
        "| # | 项目名称 | 简介 | 开发者 | Fork数 | 应用场景 | 使用方法 |",
        "|---|----------|------|--------|--------|----------|----------|",
    ]
    for i, repo in enumerate(repos, 1):
        print(f"  [{i}/{len(repos)}] Analyzing: {repo['name']}")
        analysis = analyze_project(repo)
        scenario = _esc(analysis.get("scenario", ""))
        usage = _esc(analysis.get("usage", ""))
        desc = _esc((repo["description"] or "")[:80])
        lines.append(
            f"| {i} | [{repo['short_name']}]({repo['url']}) "
            f"| {desc} "
            f"| {repo['owner']} "
            f"| {repo['forks']} "
            f"| {scenario} "
            f"| {usage} |"
        )

    lines.append("")
    lines.append("---")
    lines.append("Generated by Weekly GitHub Trending Reporter")

    return "\n".join(lines)


def main():
    print("Fetching trending repositories...")
    repos = fetch_trending(top_n=10)

    if not repos:
        print("No repos found.")
        return

    print(f"Fetched {len(repos)} repos. Analyzing with LLM...")
    report = build_report(repos)

    print("Sending email report...")
    send_report(report)

    print("Done. Report sent to email.")


if __name__ == "__main__":
    main()
